#!/usr/bin/env bash
[[ " domains domains:setup domains:add domains:clear domains:remove help domains:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/domains/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"

case "$1" in
  domains)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    domains_main "$2"
    ;;

  domains:setup)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    domains_setup "$2"
    ;;

  domains:add)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"

    if [[ -z "${*:3}" ]]; then
      echo "Usage: dokku $1 $2 DOMAIN [DOMAIN ...]"
      echo "Must specify DOMAIN."
      exit 1
    fi
    shift 1
    domains_add "$@"
    ;;

  domains:clear)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    domains_clear "$2"
    ;;

  domains:remove)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"

    if [[ -z "${*:3}" ]]; then
      echo "Usage: dokku $1 $2 DOMAIN [DOMAIN ...]"
      echo "Must specify DOMAIN."
      exit 1
    fi

    shift 1
    domains_remove "$@"
    ;;

  help | domains:help)
    cat<<EOF
    domains <app>, List custom domains for app
    domains:add <app> DOMAIN, Add a custom domain to app
    domains:clear <app>, Clear all custom domains for app
    domains:remove <app> DOMAIN, Remove a custom domain from app
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
