#!/usr/bin/env bash
[[ " checks checks:enable checks:disable help ps:help " == *" $1 "* ]] || exit $DOKKU_NOT_IMPLEMENTED_EXIT
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/checks/functions"

case "$1" in
  checks)
    checks_main $2
    ;;

  checks:enable)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    checks_enable $2 --no-restart
    ;;

  checks:disable)
    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    checks_disable $2 --no-restart
    ;;

  help | ps:help)
    cat<<EOF
    checks <app>, Show zero-downtime status
    checks:enable <app>, Enable zero-downtime checks
    checks:disable <app>, Disable zero-downtime checks
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
